### ISSUE TITLE
Bug : Export markdown as Html file not working for mmcli.exe

### ISSUE THREAD

**Issue by Trystan-SA** [RickStrahl/MarkdownMonster#1051]
I have a dozen markdown files in multiple folders. I need to render them automatically through a script using mmcli.exe. But the cli is not working properly.

I use this markdown code :
```md
# Hello Markdown #

Lorem Ipsum
```

When I run this command :
`mmcli markdowntohtml -i ".\markdown.md" -o ".\rendered.html" --rendermode html --theme Dharkan -open` 

I get this error inside the HTML page rendered :

```txt
Error
Object reference not set to an instance of an object.

at MarkdownMonster.MarkdownParserDocFxMarkdig.Parse(String markdown) in D:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\MarkdownParser\MarkdownParserDocFxMarkdig.cs:line 101
at MarkdownMonster.MarkdownDocument.RenderHtml(String markdown, Boolean usePragmaLines, Boolean noBanner) in D:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\MarkdownDocument.cs:line 1195
```

And this in the error logs :

```txt
22/06/2023 15:01:17 - Unable to render Markdown Document: Object reference not set to an instance of an object.
# Hello Markdown #

Lorem Ipsum
Object reference not set to an instance of an object.
Markdown Monster v3.0.0.13
10.0.19041.1.amd64fre.vb_release.191206-1406 - fr-FR - NET 4.8 - 64 bit
n/a, hw-acc: True
fr-FR - fr-FR    
---
MarkdownMonster
   at MarkdownMonster.MarkdownParserDocFxMarkdig.Parse(String markdown) in D:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\MarkdownParser\MarkdownParserDocFxMarkdig.cs:line 101
   at MarkdownMonster.MarkdownDocument.RenderHtml(String markdown, Boolean usePragmaLines, Boolean noBanner) in D:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\MarkdownDocument.cs:line 1195
System.NullReferenceException
---------------------------
```

But when I'm exporting it through the application UI, its working. But I still get an error popup (even if the file got rendered correctly)

![MarkdownMonster_n26x50gmAc](https://github.com/RickStrahl/MarkdownMonster/assets/43876044/3384c941-aa1f-418b-8ef8-c9aba93b0c08)

I get the same error when I'm exporting with `--rendermode html`,` packagedhtml` and `zip`. Only `fragment` seems to work. But since I need to embed pictures with my export, it’s useless for my use case.

**Comment by RickStrahl** [comment]
Can you try the regular Markdown Parser, not the DocFx one?

**Comment by RickStrahl** [comment]
FWIW, if I run this with the regular parser it works fine:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/d4263eba-9ab7-4d8e-a27d-55b88a53f627)

**Comment by Trystan-SA** [comment]
Yes its working fine now. DocFX was indeed causing the issue ! Thanks for that !

**Comment by RickStrahl** [comment]
I took a quick look and the problem is that the DocFx parser requires a bunch of context in order to render (ie. an ActiveDocument) which is why this is failing from the CLI but works when you render from the editor - there's no active document at that time when running from the CLI. I'll need to see if I can fix this, or whether I turn off the output generation for DocFx.

It actually works from within the UI - it's only in the CLI it's failing.

I think the solution is to create the actual document from the markdown file before passing to the parser.

**Comment by RickStrahl** [comment]
The problem is that the DocFx parser requires additional state that is not available in the CLI. For now I've disabled exports from the CLI if the DocFx parser is active along with a message:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/d5fbe626-2cc8-46ad-afa5-6fe8738fcd02)

If the DocFx parser output is required, it's still possible through the Main UI.
