### ISSUE TITLE
Regression: mouse drag errors?

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1117]
I got this error dialog after clicking on the "Window" menu and then clicking in the explorer window afterwards. Able to continue after clicking YES

Do you get these errors automatically or is it worth opening a bug for them?

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/547ff24e-62db-4dec-b00d-84163979fd06)

```
10.05.2024 17:31:11 - App: Value cannot be null. (Parameter 'dragSource')
Value cannot be null. (Parameter 'dragSource')
Markdown Monster v3.2.17.3
10.0.22621.1.amd64fre.ni_release.220506-1250 - en-US - NET .NET 8.0.4 - 64 bit
LENOVO 20XWCTO1WW, Intel(R) Iris(R) Xe Graphics, hw-acc: True
WebView: rt: 124.0.2478.80 - sdk: 1.0.2365.46
de-DE - en-US
C:\Program Files\Markdown Monster
Portable: False
---
PresentationCore
   at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
   at MarkdownMonster.Windows.FolderBrowerSidebar.TreeFolderBrowser_MouseMove(Object sender, MouseEventArgs e) in D:\projects\MarkdownMonsterCode\markdownmonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 1681
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.MouseDevice.Synchronize()
   at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
   at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.ArgumentNullException
---------------------------
```

**Comment by RickStrahl** [comment]
Fixed.

Was able to duplicate, now checking for the TV item selection. Oddly the click registers as a move operation (if the mouse moves enough when clicking in I guess).
