### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by uskyrt** [RickStrahl/MarkdownMonster#185]
Event viewer info:

`Application: MarkdownMonster.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.TypeLoadException Stack: at Microsoft.ApplicationInsights.Extensibility.Implementation.AsyncLocalHelpers.GetCurrentOperationContext() at Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.ApplicationInsights.TelemetryClient, System.String) at MarkdownMonster.mmApp.ApplicationStart() at MarkdownMonster.App..ctor() at MarkdownMonster.App.Main() `

Let me know if you need additional info.

**Comment by RickStrahl** [comment]
Thanks for the report. What version are you running?

Does this happen every time or one time? 

This has to do with the MS Application Insights - annything special happening on the networks you're using by any chance? Also is there anything in your log file for this particular crash (`%appdata%\Markdown Monster\MarkdownMonsterErrors.txt`).

Checking logs I see latest versions running with lots of new requests coming in and I see nothing in the logs - but then this sounds like a hard crash so we probably wouldn't see anything in the logs and definitely not in the telemetry if that's what's blowing up :-)

**Comment by uskyrt** [comment]
It happens every time. I get to the splash screen and it crashes.
No .log in C:\Users\[user]\AppData\Roaming\Markdown Monster
In the application properties it says version 1.3.3.0

Network wise. I'm on the company laptop, I've installed MM while on a VPN but relaunching on my home wifi has the same results. I've tried reinstalling on the 'normal' connection but no luck.
Any suggestion?

**Comment by RickStrahl** [comment]
I'm not sure why you are seeing this particular crash. App Insights are launched as part of the startup routine and it appears to be working on all the machines I'm testing on which are Win10, Server 2012 R2 and Win7.  

What OS and .NET version are you running just to cross reference.

I think the 'quick' fix for this would be to just wrap the AppInsights code in try/catch, but I'd like to understand what's failing - unfortunately with a hard crash that's hard to do :-(.

**Comment by RickStrahl** [comment]
I've uploaded an update (1.3.3) that does wrap the startup and disables AppInsights if it fails to initialize. Give a shot...

https://markdownmonster.west-wind.com/download.aspx

If this is a hard, hard failure in AppInsights this may still blow up, but hopefully the t/c will provide potentially more information before it dies. Any info should go to the log file mentioned above.

Let me know what you find.

**Comment by RickStrahl** [comment]
Oh and if that doesn't work - you can set the **SendTelemetry** key in **Tools -> Settings** to false (which should now be respected for AppInsights - wasn't before).

**Comment by uskyrt** [comment]
Here's the info:
Win 7 enterprise 64
.net 4
I've installed your new version but this time it crashes with a some info 'something went wrong' which disappears immediately.
I've managed to grab a screenshot:
![mm error](https://cloud.githubusercontent.com/assets/10675122/25614153/ab84ed88-2f28-11e7-8449-a2bf8458f7c6.png)
The error log:
`02/05/2017 11:09:41 - Application Insights initialization failure: Could not load type 'System.Threading.AsyncLocal`1' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
02/05/2017 11:09:42 - Last Resort Handler
Markdown Monster v1.3.3.0
6.1.7601.23714.amd64fre.win7sp1_ldr.170307-1800 - en-US - NET 4.5.2 - 32 bit
---
MarkdownMonster
   at MarkdownMonster.MainWindow.SetTabHeaderBinding(TabItem tab, MarkdownDocument document, String propertyPath)
   at MarkdownMonster.MainWindow.OpenTab(String mdFile, MarkdownDocumentEditor editor, Boolean showPreviewIfActive, String syntax, Boolean selectTab, Boolean rebindTabHeaders, Boolean batchOpen, Int32 initialLineNumber) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 427
   at MarkdownMonster.MainWindow.OnLoaded(Object sender, RoutedEventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 167
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------



02/05/2017 11:09:51 - Application Insights initialization failure: Could not load type 'System.Threading.AsyncLocal`1' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
02/05/2017 11:09:52 - Last Resort Handler
Markdown Monster v1.3.3.0
6.1.7601.23714.amd64fre.win7sp1_ldr.170307-1800 - en-US - NET 4.5.2 - 32 bit
---
MarkdownMonster
   at MarkdownMonster.MainWindow.SetTabHeaderBinding(TabItem tab, MarkdownDocument document, String propertyPath)
   at MarkdownMonster.MainWindow.OpenTab(String mdFile, MarkdownDocumentEditor editor, Boolean showPreviewIfActive, String syntax, Boolean selectTab, Boolean rebindTabHeaders, Boolean batchOpen, Int32 initialLineNumber) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 427
   at MarkdownMonster.MainWindow.OnLoaded(Object sender, RoutedEventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 167
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
`

Thanks for your help!

**Comment by RickStrahl** [comment]
I think the problem with the Tab binding is .NET 4.5.2. Any chance you can upgrade .NET to 4.6.2 (I think any version of 4.6 and later should work).

I don't have any machines to check 4.5.2 on - everything including Azure VMs pre-install with 4.6.1 these days. My Windows 7 test machine is running 4.6.1 and MM is working without issues in that environment.

Thanks for reporting - I wasn't aware that there were problems with earlier versions. I'll update the requirements.

**Comment by uskyrt** [comment]
Updated to 4.6.2 and everything works!
Thank you very much for your help and quick support, much appreciated.

**Comment by RickStrahl** [comment]
Thanks. I've updated the requirements on the download and home pages:
![image](https://cloud.githubusercontent.com/assets/1374013/25698684/a458aa34-3074-11e7-84ea-96ee40213d6d.png)

And also added a startup check that checks the version on startup and throws up a message box if running anything older than 4.6.
