### ISSUE TITLE
Tools->Addins->Screen Capture crashes when SnagIt not installed

### ISSUE THREAD

**Issue by Anaerin** [RickStrahl/MarkdownMonster#2]
Error log reports:

2016-06-06 1:27:16 PM - Object reference not set to an instance of an object.
---
ScreenCaptureAddin
   at SnagItAddin.ScreenCaptureAddin.OnCanExecute(Object sender)
   at MarkdownMonster.AddIns.AddinManager.<>c__DisplayClass10_1.<InitializeAddinsUi>b__0(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Might want to check before enabling that option.

**Comment by RickStrahl** [comment]
Well there's a check there but it looks like the check is actually failing. The add-in shouldn't be active if SnagIt is not installed. 

Eventually there will be a base capture if snagIt isn't installed but that's not there yet.

**Comment by RickStrahl** [comment]
Ok so I took a look on my bare bones machine that doesn't have SnagIt installed. The toolbar button does the right thing - it's disabled, but the Addin list still has SnagIt enabled and that crashes. 

This affects all addins - the bug is that they don't respect the CanExecute option.

**Comment by RickStrahl** [comment]
Fixed in: 69518b5

Fixed by ensuring that the addin list in the menu is also disabled.

Actual bug was that a casting error that received both menuitems and toolbars. Fixed.
