### ISSUE TITLE
Recent Files Menu Button Dropdown Throws Error

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#388]
## Applies To
MM Version: 1.11.17 (June 18 2018)

## Problem Description
Clicking the "Recent Files" dropdown button throws this error:

> Yikes! Something went wrong...
> Object reference not set to an instance of an object
> The error has been recorded and written to a log file and your can review the details or report the error via Help | Show Error Log
> Do you want to to continue?

Clicking Yes allows MM to open.

## Steps to Reproduce
1. Open MM
2. In the menu bar, click the Recent Files dropdown

## More Info

My MM is set to `"UseSingleWindow": false,`

Here's the complete log entry from a failure:

```txt
6/21/2018 9:19:34 AM - Last Resort Handler
Markdown Monster v1.11.17.0
10.0.17134.1.x86fre.rs4_release.180410-1804 - en-US - NET 4.7.2 - 32 bit
en-US - en-US    
---
MarkdownMonster
   at MarkdownMonster.MainWindow.Button_Handler(Object sender, RoutedEventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 1972
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------
```

(Rick: I *really* like the formatting you did with the recent files menu item. I don't recall seeing it in any other editor)

**Comment by RickStrahl** [comment]
I've been seeing errors with this coming in, in my error logs, but I haven't been able to pin this one down. I can't duplicate it.

Does it work from the button dropdown on the tool bar which is basically generating the same list?

Does it always fail or intermittently? Are you 'hovering' to open the Recent Files submenu, or clicking?

Any chance you can share your config file or at least the Recent Files and Recent Documents settings?

**Comment by RickStrahl** [comment]
Can you grab 1.11.17.1 from the [Web site](https://markdownmonster.west-wind.com/download.aspx) download and see if this is any better? Made a couple of defensive code adjustments although I don't think those things should ever cause a problem - essentially extra null and existence checks.

**Comment by bladewolf55** [comment]
1.11.17.1 fixed it. For the record, though, I've attached a screen cap
video of what I was doing.



--
Charles L Flatt
513-535-0764 (m)
"History has shown us that courage can be contagious, and hope can take on
a life of its own." --Michelle Obama
