### ISSUE TITLE
Error running Commander C# Script: Method not found 'SetMarkdown'

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#448]
## Environment
-   Version: 1.13 Sep 28  
-   Windows 10 Pro

## Steps
1.  Open Addin
2.  Run using "Run Command" button or keyboard shortcut

## More info

**Complete Error Message/Stack From Log**  
```txt
9/30/2018 11:24:56 AM - App Error: Method not found: 'Void MarkdownMonster.MarkdownDocumentEditor.SetMarkdown(System.String, System.Object, Boolean)'.
Method not found: 'Void MarkdownMonster.MarkdownDocumentEditor.SetMarkdown(System.String, System.Object, Boolean)'.
Markdown Monster v1.13.0.0
10.0.17134.1.x86fre.rs4_release.180410-1804 - en-US - NET 4.7.2 - 32 bit
en-US - en-US    
---
CommanderAddin
   at CommanderAddin.CommanderAddin.RunCommand(CommanderCommand command)
   at CommanderAddin.CommanderAddin.<>c__DisplayClass10_0.<OnWindowLoaded>b__0(Object s, ICommand e)
   at MarkdownMonster.CommandBase.Execute(Object parameter) in C:\projects2010\MarkdownMonster\MarkdownMonster\Controls\CommandBase.cs:line 62
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------
```

**Script**  
```csharp
#r Westwind.Utilities.dll
#r Microsoft.VisualBasic.dll
using Westwind.Utilities;
using System.IO;

var doc = Model.ActiveDocument;
var editor = Model.ActiveEditor;
var currentLineNbr = editor.GetLineNumber();

int lineNbr = 0;
bool found = false;
string token = "grateful or anticipating:";
string bullets = "";

DateTime today = DateTime.Today;

string userDate = Microsoft.VisualBasic.Interaction.InputBox("Enter DateTime (yyyy-mm-dd)","DateTime", today.ToString("yyyy-MM-dd") , 600, 300);

string dt = Convert.ToDateTime(userDate).AddDays(-7).ToString("yyyy-MM-dd");

while (lineNbr < currentLineNbr)
{
    string line = editor.GetLine(lineNbr);
    if (line.Trim().ToLower() == "## today " + dt)
    {
        found = true;
    }
    if (found) 
    {
        if (line.Trim().ToLower().StartsWith(token))
        {
            bullets += "    *   " + line.Trim().Substring(token.Length) + "\r\n";
        }
    }
    lineNbr++;
}

string wupdate = @"Weekly Update " + userDate + @"
========================
Work Highlights
---------------
*   

Personal Highlights
-------------------
*   
*   Last week's anticipating/gratitudes
" + bullets + @"

Week Starting " + userDate + @"
========================
*   
";

editor.SetSelection(wupdate);
editor.SetCursorPosition(3, currentLineNbr + 5 );
```

**Sample Data**  
```markdown
## Today 2018-09-29  

Grateful or Anticipating: Park walk somewhere with Steph and Mac

Attempting:
- [x] Clean house
- [x] When to put down winterizer
- [x] Wrap gift
- [x] Scan/capture all Joe car work. Find Honda recommended service schedule.
- [x] Clean up contacts 
- [x] Plan next month
- [ ] Read Blind Assassin

**Today.txt**  
If nothing else, today I am going to wrap Steph's gift.  
I am going to do this by finishing cleaning, then wrapping before she gets home.  
**If I do this and only this, today will be a good day.**

2018-09-29 11:41:24  

Had a nice walk with Steph and Mac at Observatory park.


## Today 2018-09-30  

Grateful or Anticipating: Steph 2nd birthday gift surprise

Attempting:
- [ ] Weekly reset
- [ ] Monthly reset
- [ ] Clean up picture Inbox 
- [ ] Research back muscle + nerves + therapy
- [ ] Read Blind Assassin (Sun, finish!)

**Today.txt**  
If nothing else, today I am going to read 100 pages of *The Blind Assassin*.  
I am going to do this by completing my other tasts, then lying on the couch and reading.  
**If I do this and only this, today will be a good day.**
```

**Comment by RickStrahl** [comment]
Ah yes - update in the MM automation interface caused this. Addin needed to be recompiled.

Update the addin and it should now work.

**Comment by bladewolf55** [comment]
Brilliant! Working, now, thank you. Sorry to interrupt your Sunday.

--
Charles L Flatt
513-535-0764 (m)

"To admit uncertainty is to admit to weakness, to powerlessness, and to
believe in yourself despite both. It is a frailty, but in this frailty
there is a strength: the conviction to live in your own mind, and not in
someone else’s." --Tara Westover, Educated
