### ISSUE TITLE
v1.14.7 Crashes if editor-user-extensions.js includes var ace = window.textEditor.editor;

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#473]
**Description** MM's editor pane doesn't display editor when opening, and throws error when clicked.

**Steps**
1. Close MM.
2. Create or open the new `editor-user-extensions.js` file.
3. Enter only `var ace = window.textEditor.editor;`
4. Save
5. Open MM and click New Document. The editor doesn't appear (there's no cursor).
6. Click on the editor pane and error is thrown.

"Yikes! etc..."

**More Information**  

Here is the complete error log.

```txt
1/6/2019 11:31:38 AM - AppDispatcher Error: Exception from HRESULT: 0x80020101
Exception from HRESULT: 0x80020101
Markdown Monster v1.14.7.0
10.0.17763.1.x86fre.rs5_release.180914-1434 - en-US - NET 4.7.2 - 32 bit
en-US - en-US    
---
mscorlib
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure , CallSite , ComObject , Boolean )
   at CallSite.Target(Closure , CallSite , Object , Boolean )
   at MarkdownMonster.MarkdownDocumentEditor.SetEditorFocus() in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\MarkdownDocumentEditor.cs:line 1382
   at MarkdownMonster.MainWindow.TabControl_OnPreviewMouseLeftButtonUp(Object sender, MouseButtonEventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 2781
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnPreviewMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------
```

**Comment by RickStrahl** [comment]
That won't work because ACE Editor isn't initialized at the time that that code runs.

You can do:
```js
var te = window.textEditor;
te.myFunction = function() {
   var aceEditor = te.editor;
}
```

As to the crash: MM shouldn't crash on a JavaScript error - those are silently skipped. However I think that `ace` is a magic variable for ACE editor and assigning it as you do I can duplicate the crash due to missing ACE Editor functionality which eventually fails to render the document. Using a different varname - `aceEditor` for example doesn't crash.
