### ISSUE TITLE
application fails to start following setup (windows 7, 32-bit)

### ISSUE THREAD

**Issue by jcbrill** [RickStrahl/MarkdownMonster#502]
Following installation, the application terminates during startup on a 32-bit windows 7 box.

Git may be present on path due to Visual Studio 2017 installation options but has never been setup and/or configured and there are no local repositories.  Multiple install/invocation attempts changing the path (i.e., removing git folder, minimal system path, etc) did not appear to make any difference.

Windows event viewer reports:
```
Application: MarkdownMonster.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.IO.Path.Combine(System.String, System.String)
   at MarkdownMonster.mmFileUtils.FindGitDiffTool()
   at MarkdownMonster.ApplicationConfiguration.OnInitialize(Westwind.Utilities.Configuration.IConfigurationProvider, System.String, System.Object)
   at Westwind.Utilities.Configuration.AppConfiguration.Initialize(Westwind.Utilities.Configuration.IConfigurationProvider, System.String, System.Object)
   at MarkdownMonster.mmApp..cctor()

Exception Info: System.TypeInitializationException
   at MarkdownMonster.mmApp.HandleApplicationException(System.Exception, MarkdownMonster.ApplicationErrorModes)
   at StartUp.Main()

```

**Comment by RickStrahl** [comment]
Ah thank you, I see what the problem is. Code assumes 64 bit folder and fails due to not finding the 64 bit program files folder.

Fixing. Should have a patch up shortly. Look for 1.16.7 or later.

**Comment by jcbrill** [comment]
Problem fixed.  Thank you.
