### ISSUE TITLE
`AppDispatcher Error: The directory name  is invalid.` when creating a new file

### ISSUE THREAD

**Issue by breki** [RickStrahl/MarkdownMonster#572]
Version 1.19.4

Every time I try to create a new file inside MM, I get multiple error dialogs and these kinds of entries in the error log:
```
14. 09. 2019 08:11:29 - AppDispatcher: The directory name  is invalid.
The directory name  is invalid.
Markdown Monster v1.19.4.0
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 39
   at MarkdownMonster.AppModel.get_ActiveEditor() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 94
   at MarkdownMonster.MainWindow.DocumentType_SelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 2715
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at MarkdownMonster.AppModel.OnPropertyChanged(String propertyName) in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 545
   at MarkdownMonster.AppModel.set_ActiveDocument(MarkdownDocument value) in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 131
   at MarkdownMonster.MainWindow.TabControl_SelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 1305
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.TabControl.OnSelectionChanged(SelectionChangedEventArgs e)
   at Dragablz.TabablzControl.OnSelectionChanged(SelectionChangedEventArgs e) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 716
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.Selector.set_SelectedItem(Object value)
   at MarkdownMonster.MainWindow.OpenTab(String mdFile, MarkdownDocumentEditor editor, Boolean showPreviewIfActive, String syntax, Boolean selectTab, Boolean rebindTabHeaders, Boolean batchOpen, Int32 initialLineNumber, Boolean readOnly, Boolean noFocus, Boolean isPreview) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 1269
   at MarkdownMonster.AppCommands.<NewDocument>b__12_0(Object s, ICommand e) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Commands\AppCommands.cs:line 146
   at MarkdownMonster.CommandBase.Execute(Object parameter) in C:\projects2010\MarkdownMonster\MarkdownMonster\Controls\CommandBase.cs:line 84
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------



14. 09. 2019 08:11:29 - AppDispatcher: The directory name  is invalid.
The directory name  is invalid.
Markdown Monster v1.19.4.0
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 39
   at MarkdownMonster.AppModel.get_ActiveEditor() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 94
   at MarkdownMonster.MainWindow.OnDeactivated(EventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 511
   at System.Windows.Window.HandleActivate(Boolean windowActivated)
   at System.Windows.Window.WmActivate(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------



14. 09. 2019 08:11:29 - AppDispatcher: The directory name  is invalid.
The directory name  is invalid.
Markdown Monster v1.19.4.0
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 39
   at MarkdownMonster.AppModel.get_ActiveEditor() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 94
   at MarkdownMonster.AppModel.get_IsEditorActive() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 218
   at MarkdownMonster.AppCommands.<Save>b__27_1(Object s, ICommand e) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Commands\AppCommands.cs:line 347
   at MarkdownMonster.CommandBase.CanExecute(Object parameter) in C:\projects2010\MarkdownMonster\MarkdownMonster\Controls\CommandBase.cs:line 66
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RequerySuggestedEventManager.OnRequerySuggested(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------
```

**Comment by RickStrahl** [comment]
Hmmm... yes this is related to the new file watcher that is attached to the active editor.

However, I can't duplicate this. Can you give me steps of what you do when this fails?

I tried:

* Ctrl-N to create a new Document
* Ctrl-s to save and type in a new filename
* File saves without issue

I can see that the FileWatcher would fail to work if the path is invalid and that needs to be fixed, but I not even sure how to get to that point unless I type an invalid file path?

Let me know steps to help isolate the path to get to the failure you see. 

Thank you!

**Comment by RickStrahl** [comment]
So taking a look at this I'm puzzled how this could actually happen as the code explicitly checks for whether the file exists:

```cs
public static void AttachFilewatcher(MarkdownDocumentEditor document)
{
    var file = document?.MarkdownDocument?.Filename;
    if (file == null || !File.Exists(file))
        return;

    if (FileWatcher == null)
    {
        var folder = Path.GetDirectoryName(file);
        
        try
        {
            FileWatcher = new FileSystemWatcher();
            FileWatcher.Path = folder;
            FileWatcher.Filter = Path.GetFileName(file);
            FileWatcher.NotifyFilter = NotifyFilters.LastWrite;
            FileWatcher.EnableRaisingEvents = true;
            FileWatcher.Changed += FileWatcher_Changed;
        }
        catch(Exception ex)
        {
            mmApp.Log($"Couldn't attach File Watcher to active document: {folder}", ex,logLevel: LogLevels.Error);
        }
    }
    else
    {
        FileWatcher.Path = Path.GetDirectoryName(file);
        FileWatcher.Filter = Path.GetFileName(file);
    }
}
```

I added the try/catch block now which should prevent the failure you see, but I'm puzzled by what would cause the failure to occur. I wonder if it's a permissions issue or some specially mapped folder that's causing issues with the path assignment? Or an odd filename where the folder name is incorrect?

The new code will log the filename so that might help isolate the problem.

**Comment by breki** [comment]
Hi,

I can't really tell you how to reproduce it, but one piece of information I
can give you is that it does NOT happen when I create a new document in an
empty instance of MM ("empty" meaning no other documents are open in MM).
As soon as I open one of the recent documents and then try to create a
document, it crashes as described.

**Comment by breki** [comment]
OK, I tried MM on a different machine (and same MM version), and it works
without problems. Could it be a corrupted MM configuration or something?

**Comment by RickStrahl** [comment]
I wonder if it might have something to do with permissions?

I just updates the download version on the site that includes the try/catch block and extra logging. Can you try that one - that should fix the problem, but it will also provide some additional info on my end via the logs.

**Comment by breki** [comment]
Still crashes. Sending you the latest logs:

```
14. 09. 2019 20:36:12 - AppDispatcher: The directory name  is invalid.
The directory name  is invalid.
Markdown Monster v1.19.4.2
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 41
   at MarkdownMonster.AppModel.get_ActiveEditor() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 94
   at MarkdownMonster.AppModel.get_IsEditorActive() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 218
   at MarkdownMonster.AppCommands.<Save>b__27_1(Object s, ICommand e) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Commands\AppCommands.cs:line 347
   at MarkdownMonster.CommandBase.CanExecute(Object parameter) in C:\projects2010\MarkdownMonster\MarkdownMonster\Controls\CommandBase.cs:line 66
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RequerySuggestedEventManager.OnRequerySuggested(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------



14. 09. 2019 20:36:12 - AppDispatcher: The directory name  is invalid.
The directory name  is invalid.
Markdown Monster v1.19.4.2
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 41
   at MarkdownMonster.AppModel.get_ActiveEditor() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 94
   at MarkdownMonster.MainWindow.OnDeactivated(EventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 511
   at System.Windows.Window.HandleActivate(Boolean windowActivated)
   at System.Windows.Window.WmActivate(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------



14. 09. 2019 20:36:14 - AppDispatcher: The directory name  is invalid.
The directory name  is invalid.
Markdown Monster v1.19.4.2
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 41
   at MarkdownMonster.AppModel.get_ActiveEditor() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 94
   at MarkdownMonster.MainWindow.OnActivated(Object sender, EventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 538
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Window.OnActivated(EventArgs e)
   at System.Windows.Window.HandleActivate(Boolean windowActivated)
   at System.Windows.Window.WmActivate(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------



14. 09. 2019 20:36:14 - AppDispatcher: The directory name  is invalid.
The directory name  is invalid.
Markdown Monster v1.19.4.2
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 41
   at MarkdownMonster.AppModel.get_ActiveEditor() in C:\projects2010\MarkdownMonster\MarkdownMonster\AppModel.cs:line 94
   at MarkdownMonster.MainWindow.OnDeactivated(EventArgs e) in C:\projects2010\MarkdownMonster\MarkdownMonster\MainWindow.xaml.cs:line 511
   at System.Windows.Window.HandleActivate(Boolean windowActivated)
   at System.Windows.Window.WmActivate(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------
```

**Comment by RickStrahl** [comment]
I must be asleep still - duh. Missed the secondary attachment case for the exception handler. Updated again. Sorry about that.

**Comment by breki** [comment]
The error log is now full (and I mean 230 entries for just clicking Ctrl+N once or twice) of these entries:
```
15. 09. 2019 07:08:51 - Couldn't attach File Watcher to active document: 
The directory name  is invalid.
Markdown Monster v1.19.4.6
10.0.18362.239.x86fre.19h1_release_svc_prod1.190628-1641 - en-US - NET 4.8 - 32 bit
sl-SI - en-US    
---
System
   at System.IO.FileSystemWatcher.set_Path(String value)
   at MarkdownMonster.Utilities.DocumentFileWatcher.AttachFilewatcher(MarkdownDocumentEditor document) in C:\projects2010\MarkdownMonster\MarkdownMonster\_Classes\Utilities\DocumentFileWatcher.cs:line 37          
---------------------------
```

**Comment by RickStrahl** [comment]
I can see the errors in the log, but it's showing an empty string for the folder which is weird because MM checks for the file existance before attaching the file watcher. I also changed the logging to log the whole file name.

Is there any thing special about the files you are working with? Network drive? Online drive? Low permissions?

Everything is bracketed now - the bunch of errors you see are actually gated and other than flooding the log they are not causing an issue. Still not sure why a valid file would cause a problem here though and even weirder when you say it doesn't happen on another machine with the same version.

The only thing I can think of is some weird permissions issue that disallows directory read access perhaps?

Checked my reporting logs and I don't see anybody else having run into this - this seems like something that would trigger  a lot of people if it were a common problem.

**Comment by breki** [comment]
No, nothing special about permissions - my account is actually a local admin and the files I'm working on are on other (non-system) local drives. I do also use a Boxcryptor drive, but that's the same on the other machine where there are no problems.

Anyway, the latest pre-release (.8) doesn't report any errors in the log, so I can't really give you any new info about this issue. Unless you want to do some more diagnostics on it, you can close the issue as far as I'm concerned. Thanks for taking the time to work on this issue!

**Comment by RickStrahl** [comment]
I added another couple of checks for empty files and untitled (ie. no file to monitor) that now exits immediately. It's possible that somehow the `untitled` filename was a problem - possibly you have a file name untitled so it exists, and then the empty path is invalid.

I dunno. But thanks for sticking with this. I don't see other entries for this so this seems like an isolated issue thankfully.
