### ISSUE TITLE
Bug when post to Medium

### ISSUE THREAD

**Issue by stranger777** [RickStrahl/MarkdownMonster#684]
MM wants not-null value when posts to Medium. I pressed "Post to Weblog" and it occured. Earlier I can't post due to TLS/SSL also. I have integration token. I will write a test-case if you needed.

19.08.2020 13:33:42 - AppDispatcher: Value cannot be null.
Parameter name: value
Value cannot be null.
Parameter name: value
Markdown Monster v1.23.17.0
6.1.7601.23807.amd64fre.win7sp1_ldr.170512-0600 - ru-RU - NET 4.8 - 32 bit
ru-RU - ru-RU    

Newtonsoft.Json
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at WebLogAddin.Medium.MediumApiClient.GetUser() in C:\projects\MarkdownMonster\AddIns\WebLogAddin\Medium\MediumApiClient.cs:line 106
   at WebLogAddin.Medium.MediumApiClient..ctor(WeblogInfo weblogInfo) in C:\projects\MarkdownMonster\AddIns\WebLogAddin\Medium\MediumApiClient.cs:line 79
   at WeblogAddin.WebLogAddin.<SendPost>d__14.MoveNext() in C:\projects\MarkdownMonster\AddIns\WebLogAddin\WebLogAddin.cs:line 268
 
End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WeblogAddin.WeblogForm.<ButtonPostBlog_Click>d__10.MoveNext() in C:\projects\MarkdownMonster\AddIns\WebLogAddin\WebLogForm.xaml.cs:line 134

End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RickStrahl** [comment]
Thank you for reporting. I suspect the problem here is that the URL is incorrect and that fails so part of this is the correct behavior :smile:

The bug here is actually in the HTTP component (my Westwind HTTP client) and it's supposed to eat the exception and return error information, but that's not happening. I've updated the Http client to properly handle the exceptions (based on the ThrowExceptions flag) so going forward we should get error messages instead of a crash.

Check again in the next update (post >1.23.17.3)

**Comment by stranger777** [comment]
This bug fixed. Thanks! But now we have a new bug.
