### ISSUE TITLE
Unable to render Markdown Document

### ISSUE THREAD

**Issue by anders-eriksson** [RickStrahl/MarkdownMonster#742]
### Unable to render Markdown Document

An error occurred trying to parse the Markdown document to HTML. 

**Error**
The type initializer for 'MarkdownMonster.AddIns.BaseAddinConfiguration`1' threw an exception. 

**Error detail**

> at PanDocMarkdownParserAddin.PandocMarkdownParser..ctor() in C:\projects\MarkdownMonsterAddins\PanDocMarkdownParserAddin\PanDocMarkdownParserAddin\PandocMarkdownParser.cs:line 16
> at PanDocMarkdownParserAddin.PanDocMarkdownParserAddin.GetMarkdownParser() in C:\projects\MarkdownMonsterAddins\PanDocMarkdownParserAddin\PanDocMarkdownParserAddin\PanDocMarkdownParserAddin.cs:line 44
> at MarkdownMonster.AddIns.MarkdownMonsterAddin.GetMarkdownParser(Boolean usePragmaLines, Boolean force) in C:\projects\MarkdownMonster\MarkdownMonster\_Classes\AddInInterfaces\MarkdownMonsterAddin.cs:line 340
> at MarkdownMonster.MarkdownParserFactory.GetParser(Boolean usePragmaLines, Boolean forceLoad, String parserAddinId) in C:\projects\MarkdownMonster\MarkdownMonster\_Classes\MarkdownParser\MarkdownParserFactory.cs:line 41
> at MarkdownMonster.MarkdownDocument.RenderHtml(String markdown, Boolean usePragmaLines, Boolean noBanner) in C:\projects\MarkdownMonster

**from log file**

> 
> Method not found: 'Void MarkdownMonster.AddIns.BaseAddinConfiguration`1.set_ConfigurationFilename(System.String)'.
> Markdown Monster v1.25.14.0
> 10.0.19041.1.x86fre.vb_release.191206-1406 - en-US - NET 4.8 - 32 bit
> sv-SE - en-US    
> ---
> PandocMarkdownParserAddin
>    at PanDocMarkdownParserAddin.PandocAddinConfiguration..ctor()  

PandocMarkdownParserAddin version 0.3.10

The error started all of a sudden in the last version! I updated to version 1.25.14, but the error is still there

**Comment by anders-eriksson** [comment]
I uninstalled MarkdownMonster and the Pandoc addin
I then resinstalled MarkdownMonster and added the pandoc addin via the Tools menu. Still the same problem!
I the cloned the pandoc addin repo and recompiled it and now everything works!
