### ISSUE TITLE
Error when changing theme

### ISSUE THREAD

**Issue by Andis59** [RickStrahl/MarkdownMonster#745]
MM 1.25.15

I get this error when changing theme.
First I get a dialog saying that MM need to restart, then the error occurs

From the log file

```
2021-01-09 10:26:30 - AppDispatcher: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v1.25.15.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 32 bit
sv-SE - en-US    
---
MarkdownMonster
   at MarkdownMonster.AppCommands.<>c.<SwitchTheme>b__327_0(Object parameter, ICommand command) in C:\projects\MarkdownMonster\MarkdownMonster\_Classes\Commands\AppCommands.cs:line 2274
   at MarkdownMonster.CommandBase.Execute(Object parameter) in C:\projects\MarkdownMonster\MarkdownMonster\Controls\CommandBase.cs:line 84
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)          
---------------------------

```

**Comment by RickStrahl** [comment]
Hmmm... interesting. Does this error occur when MM shuts down or when it tries to restart? It looks this happens before it shuts down right?

I see different behavior: Dialog pops up to change the theme, MM shuts down, and tries to restart (splash screen shows) but then terminates immediately. Restarting then works. But I don't see a crash in anywhere.

What I see on my end looks like a timing issue where the Single instance handler is not shut down yet before the new instance is launching I think.

Looking at the code I don't see any thing obvious that could be even failing with a reference exception.

One question: Are you running in multi-instance mode? ie. MM opens new windows when launched externally? I suspects what may be causing this problem and I've added a safeguard for that now as well.

**Comment by Andis59** [comment]
On 2021-01-09 21:19, Rick Strahl wrote:
>
> Hmmm... interesting. Does this error occur when MM shuts down or when 
> it tries to restart? It looks this happens before it shuts down right?
>
The error occurs before MM shuts down.
The theme change is performed if I manually restart MM.
>
> I see different behavior: Dialog pops up to change the theme, MM shuts 
> down, and tries to restart (splash screen shows) but then terminates 
> immediately. Restarting then works. But I don't see a crash in anywhere.
>
> What I see on my end looks like a timing issue where the Single 
> instance handler is not shut down yet before the new instance is 
> launching I think.
>
> Looking at the code I don't see any thing obvious that could be even 
> failing with a reference exception.
>
> One question: Are you running in multi-instance mode? ie. MM opens new 
> windows when launched externally? I suspects what may be causing this 
> problem and I've added a safeguard for that now as well.
>
I changed the settings to *Use Single Window* and now it works!

**Comment by RickStrahl** [comment]
Thanks. Yes I found and fixed the problem.

342ee63c

Also fixed the launch delay issue I was seeing, so all of this should work better now.
