### ISSUE TITLE
Add-in's. File in use intermittently while updating files being watched by sidebar

### ISSUE THREAD

**Issue by GraniteStateHacker** [RickStrahl/MarkdownMonster#747]
Appears to be a race condition in contention with updating files being watched by the file watcher in the sidebar in Add-In code.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_status_file(RepositoryHandle repo, FilePath path)
   at LibGit2Sharp.Repository.RetrieveStatus(String filePath)
   at MarkdownMonster.Utilities.GitHelper.GetGitStatusForFile(String file) in C:\projects\MarkdownMonster\MarkdownMonster\_Classes\Utilities\GitHelper.cs:line 71
   at MarkdownMonster.Windows.FolderBrowerSidebar.<>c__DisplayClass37_0.<FileWatcher_Changed>b__0() in C:\projects\MarkdownMonster\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 325
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority)
   at MarkdownMonster.Windows.FolderBrowerSidebar.FileWatcher_Changed(Object sender, FileSystemEventArgs e) in C:\projects\MarkdownMonster\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 317
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by GraniteStateHacker** [comment]
My work-around is to wrap the add-in code in a Dispatcher.InvokeAsync, which effectively marshals the add-in process onto the same thread, avoiding the contention.

**Comment by GraniteStateHacker** [comment]
If the file watcher code must perform locking operations on the files under observation, can a SyncRoot or similar mechanism be exposed that the add-in can lock() ?

**Comment by GraniteStateHacker** [comment]
> My work-around is to wrap the add-in code in a Dispatcher.InvokeAsync, which effectively marshals the add-in process onto the same thread, avoiding the contention.

I thought this was operable, but it's not. In retrospect the add-in OnExecute() is probably already on the dispatcher thread?

I think the only real workaround until LibGit2Sharp is updated will be to do file manipulations in temp folders, for now.

**Comment by RickStrahl** [comment]
What exactly are you doing in your addin?

Anything you do in the addin that affects the UI (directly or indirectly) you need to make sure happens on the UI thread so requires Dispatcher operations. A file change on its own if it pushes into the main MM code should automatically manage the marshalling. It's possible there's a place where this is not happening. But without more info on what you're doing that triggers this it's hard to say.

**Comment by GraniteStateHacker** [comment]
I'm not directly interacting with the UI, but because there's a file watcher on the files in the side bar, when I write to one of those files, an event fires.  The contention isn't actually even UI related.  It's actually LibGit2Sharp that tries to get a lock on the file I wrote to when I need to read it again.

**Comment by RickStrahl** [comment]
Can you check this again in the most recent version?

I've added some logic to capture the Git refresh error and if it occurs retry a few times. If this is a file contention error, this should fix the problem by doing slightly delayed retries.
