### ISSUE TITLE
Error editing table

### ISSUE THREAD

**Issue by paulomorgado** [RickStrahl/MarkdownMonster#802]
I'm getting this error when trying to edit or format a table:

```text
2021-05-18 16:06:39 - AppDispatcher: Length cannot be less than zero.
Parameter name: value
Length cannot be less than zero.
Parameter name: value
Markdown Monster v1.27.6.0
10.0.21382.1.amd64fre.co_release.210511-1416 - en-US - NET 4.8 - 32 bit
pt-PT - en-US    
---
mscorlib
   at System.Text.StringBuilder.set_Length(Int32 value)
   at MarkdownMonster.Windows.TableParserHtml.ParseMarkdownGridTableToData(String tableMarkdown) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\TableEditor\TableParserHtml.cs:line 388
   at MarkdownMonster.Windows.TableParserHtml.ParseMarkdownToData(String tableMarkdown) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\TableEditor\TableParserHtml.cs:line 253
   at MarkdownMonster.Windows.TableEditorHtml.ParseHtmlAndRender(String markdownOrHtmlTable) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\TableEditor\TableEditorHtml.xaml.cs:line 280
   at MarkdownMonster.Windows.TableEditorHtml..ctor(String tableMarkdownOrHtml) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\TableEditor\TableEditorHtml.xaml.cs:line 104
   at MarkdownMonster.MarkdownDocumentEditor.EditorSelectionOperation(String action, String text) in C:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\MarkdownDocumentEditor.cs:line 1210
   at MarkdownMonster.Controls.ContextMenus.EditorContextMenu.<CheckForTable>b__19_0(Object o, RoutedEventArgs args) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Controls\ContextMenus\EditorContextMenu.cs:line 632
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)     
```

**Comment by RickStrahl** [comment]
Hi - can you give a little more context? 

What exactly are you doing for it to fail? Specific table you can provide? I can't duplicate just by editing or formatting which works for me.

**Comment by RickStrahl** [comment]
Looking at the error and code that blows up this seems to suggest you have an unbalanced table that has missing columns in some of the rows. 

I've added some code to prevent this particular error, but it would still be good to have an example of code that blows up - I've not been able to duplicate the error even with an unbalanced table.

**Comment by RickStrahl** [comment]
Ok so I have a fix for what I describe which is a mismatched table. This should now work. Give this another try in 1.27.6.2 (Preview) or later.

**Comment by paulomorgado** [comment]
Hi @RickStrahl.

Where can I download 1.25.6.2 from?

**Comment by RickStrahl** [comment]
Go to the download page and click on the small preview release link to the right...

**Comment by RickStrahl** [comment]
Looked at your sample you sent and found the issue. Take another look with 1.27.7.2+...

I fixed the issue previously for Pipe Tables but missed Grid tables.  Fixed. Also added pre-selection of the active table type (ie. grid table/pipe/html) depending on what the original table was. Previously it always defaulted to Pipe Table (most common).

**Comment by RickStrahl** [comment]
Just as a side note: Grid Tables don't display on GitHub so unless you plan on using some viewer or engine that can properly display Grid Tables, Grid Tables are often not the best choice for table.

**Comment by RickStrahl** [comment]
Closing since I think this is fixed. You can re-open if you still have an issue.

Thanks for your help.
