### ISSUE TITLE
`System.ComponentModel.Win32Exception: The system cannot find the file specified` when running `mmcli install-webview`

### ISSUE THREAD

**Issue by sharpninja** [RickStrahl/MarkdownMonster#840]
Full Exception:

```
PS C:\_OneTeam\git-svn\Prod> sudo mmcli install-webview

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Westwind.Utilities.ShellUtils.ShellExecute(String url, String arguments, String workingFolder, String verb) in C:\projects\Westwind.Utilities\Westwind.Utilities\Utilities\ShellUtils.cs:line 425
   at mmcli.CommandLine.CommandLineProcessor.<HandleCommandLineArguments>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at mmcli.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at mmcli.Program.Main(String[] args)
```

**Comment by RickStrahl** [comment]
Fixed for 2.0.10. Didn't update the CLI utility for the new path in `BinSupport`.

Thank you!
