### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by tjdennis** [RickStrahl/MarkdownMonster#855]
Hi,
Getting the following exception in the latest version.

9/21/2021 7:56:29 PM - TaskExecution: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v2.0.15.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-US - en-US    
---
MarkdownMonster
   at MarkdownMonster.MainWindow.<<TabControl_SelectionChanged>b__74_0>d.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\MainWindow.xaml.cs:line 1297
System.NullReferenceException
---------------------------

9/21/2021 7:56:49 PM - AppDispatcher: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v2.0.15.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-US - en-US    
---
MarkdownMonster
   at MarkdownMonster.Windows.FolderBrowerSidebar.TextFileOrFolderName_ToolTipOpening(Object sender, ToolTipEventArgs e) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 1920
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent(Boolean fromKeyboard)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------

**Comment by RickStrahl** [comment]
Can you confirm that this occurs when you hover over the root path element (`..`) in the tree? Or something else? If it's the former that's been fixed already, but not updated yet.
