### ISSUE TITLE
Add-on somehow causing odd null reference error

### ISSUE THREAD

**Issue by deanebarker** [RickStrahl/MarkdownMonster#859]
I'm getting an error when I open a new Markdown document. It has something to do with my add-on, but I can't figure out what.

When I open a new `.md` document (and _only_ `.md`), I get a pop-up dialog that says this:

>Yikes! Something went wrong...
>
>Object reference not set to an instance of an object.
>
>The error has been recorded and written to a log file and you can review the details or report the error via Help | Show Error Log
>
>Do you want to continue?

I click "Yes," then I get the same dialog again (but always shifted a little up and to the left), then I click "Yes" again, and then it works normally.

The error log has this:

```
9/24/2021 6:05:14 AM - AppDispatcher: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v2.0.9.2
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-US - en-US    
---
MarkdownMonster
   at MarkdownMonster.MainWindow.<ActivateTab>d__81.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MarkdownMonster.MainWindow.<OpenFile>d__72.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\MainWindow.xaml.cs:line 972
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MarkdownMonster.Windows.FolderBrowerSidebar.<OpenFile>d__40.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 421
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MarkdownMonster.Windows.FolderBrowerSidebar.<HandleItemSelection>d__51.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 681
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MarkdownMonster.Windows.FolderBrowerSidebar.<TreeViewItem_MouseDoubleClick>d__65.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 1060
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------
```

It has _something_ to do with my add-in, because when I got to Settings and disable add-on loading, it works without error.

Debugging does not show any exceptions other than XAML binding exceptions (as the log shows).

Also weird: when I debug _and set a breakpoint in the Markdown parser_, it doesn't occur. So if I put a breakpoint at the top of `Parse`, and it hits, if I press play, the document opens without error. If I don't set the breakpoint, the error happens.

So, it has something to do with timing? Like, the breakpoint gives MM some time to...catch-up? Like there's something that still `null` for a couple of milliseconds when the document opens without delay, but a breakpoint slows it down the point where it works?

(But, alas, putting 'Thread.Sleep(50)' in the constructor for the Markdown parser didn't help...)

**Comment by RickStrahl** [comment]
You need to use async code for these operations. But more importantly, the tabs open asynchronously and while you can get the tab back pretty quickly the document may not be immediately loaded. So if you load and then immediately fire away at the document in the editor you might get exceptions.

This is an unfortunate side effect of the recent conversion to the Edge `WebView2` control, which is much slower at loading up especially on first load than the old code.

`Thread.Sleep()` is probably not a good idea, because it ties up the event loop and potentially slows the WebView loading even more, but you can use Dispatcher.Delay(500, ()=> { });  to do this.

Alternately there's an event you can handle on the editor that tells you when the document has loaded: `TabLoadingCompleted`.


Here's an example of how I open the configuration JSON document and then use the search functionality to jump to a keyword in the document (which requires that the doc is loaded in the editor):

```cs
var tab = await Model.Window.OpenTab(file, syntax: "json", selectTab: true, noFocus: false);
if (tab.Tag is MarkdownDocumentEditor editorTab && searchFor != null)
{
    editorTab.TabLoadingCompleted = (editor) =>
    {
        if (searchFor != null)
        {
            if (Model.ActiveEditor.EditorHandler.JsInterop != null)
                Model.ActiveEditor.EditorHandler.JsInterop.FindText(searchFor).FireAndForget();
        }
        return Task.CompletedTask;
    };
}
```


I need to update the add-in docs, to document these things better, which has been of my list to do, but I just haven't gotten around to it yet.

**Comment by deanebarker** [comment]
The thing is, I don't have any code tied to the opening of a document. The only base methods I'm overriding are `OnApplicationStart` and `OnAfterSaveDocument` and `GetMarkdownParser`.

Does `GetMarkdownParser` get called after a document opens?

**Comment by RickStrahl** [comment]
Not sure. Can you try this in the latest version please? I've been doing some work around addins that might have fixed this (has to do with async forwarding and tab activation)... also there's better exception trapping in more recent versions around the various async tab operations.
