### ISSUE TITLE
Object reference not set to an instance of an object (v2.0.15.0)

### ISSUE THREAD

**Issue by ianrussellsoftwarepark** [RickStrahl/MarkdownMonster#860]
26/09/2021 20:37:29 - AppDispatcher: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v2.0.15.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-GB - en-US    
---
MarkdownMonster
   at MarkdownMonster.Windows.FolderBrowerSidebar.TextFileOrFolderName_ToolTipOpening(Object sender, ToolTipEventArgs e) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:line 1920
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent(Boolean fromKeyboard)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------

**Comment by RickStrahl** [comment]
Thanks - can you try this again in 2.0.15.2, please?

Just to verfify - was this happening when hovering over the `..` root folder node in the folder browser - this was a known issue and fixed in recent updates.

**Comment by RickStrahl** [comment]
Closing as this has been reported before and should be fixed. Please re-open if it still happens in 2.0.16 and later.
