### ISSUE TITLE
Null Reference Error on Inserting Image from Dropbox on Mac Share

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#943]
Version 2.4.8.4

Not really sure you care about errors when accessing a mac share (from parallels) to a dropbox folder.  But if so...

- press "insert image" button on toolbar
- choose dialog open file
- get crash

I went through the steps again after MM crashed and did not get the error again, but it did leave a log file so I thought I'd attach anyhow.

![](not-responsive-keyboard-demo.gif)

```
4/17/22 9:27:01 AM - AppDispatcher: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v2.4.8.4
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-US - en-US    
---
MarkdownMonster
   at MarkdownMonster.Windows.PasteImageWindow.PasteImage_Loaded(Object sender, RoutedEventArgs e) in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\PasteImageWindow.xaml.cs:line 230
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------
```

**Comment by RickStrahl** [comment]
I took a look at that line of code and it looks like it has something to do with the clipboard when the form loads. Basically MM looks to see if you have an image URL on the clipboard and if you do tries to pre-set the link and show the image.

I added the null check in the code below, which I think that was what was blowing up for you at line 230. 

That makes no sense since the code checks for text before reading the value  but it looks like `clip` ends up as `null` which caused your error. It might be that the text on the clipboard is some special kind that's not being picked up as text... 

IAC the following code should handle that funky oddity:

```cs
else if (string.IsNullOrEmpty(Image) && Clipboard.ContainsText())
{
    string clip = ClipboardHelper.GetText()?.ToLower();
    if (clip != null &&
        (clip.StartsWith("http://", StringComparison.InvariantCultureIgnoreCase) ||
         clip.StartsWith("https://", StringComparison.InvariantCultureIgnoreCase)) &&
        (clip.Contains(".png", StringComparison.InvariantCultureIgnoreCase) ||
         clip.Contains("jpg", StringComparison.InvariantCultureIgnoreCase)))
    {
        TextImage.Text = clip;
        SetImagePreview(clip);
    }
}
```

Always a possibility that the code reference isn't the right line but the other surrounding code doesn't look like it could possibly throw a null ref exception.
