### ISSUE TITLE
MM Crush On Repetative Run of Commander Command Line Execution Launcher

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#955]
If I open the Commander Command Line Execution Launcher and click to run "Console Test" several times in a row then MM crushes after displaying:
```
---------------------------
Markdown Monster Error
---------------------------
Yikes! Something went wrong...

Method not found: 'Void MarkdownMonster.MainWindow.ShowStatus(System.String, Int32, FontAwesome.WPF.FontAwesomeIcon, System.Windows.Media.Color, Boolean)'.

The error has been recorded and written to a log file and you can review the details or report the error via Help | Show Error Log

Do you want to continue?
---------------------------
Yes   No   
---------------------------
```
I clicked several times because there was no response to the action.
PS: the menu item name is way too long in my view and does not convey the purpose

**Comment by ArthurZ** [comment]
To supplement the above, I checked the error log and found this:
`
2022-05-08 8:26:52 PM - TaskExecution: Method not found: 'Void MarkdownMonster.MainWindow.ShowStatus(System.String, Int32, FontAwesome.WPF.FontAwesomeIcon, System.Windows.Media.Color, Boolean)'.
Method not found: 'Void MarkdownMonster.MainWindow.ShowStatus(System.String, Int32, FontAwesome.WPF.FontAwesomeIcon, System.Windows.Media.Color, Boolean)'.
Markdown Monster v2.4.13.0
10.0.22000.1.amd64fre.co_release.210604-1628 - en-US - NET 4.8 - 64 bit
en-CA - en-US    
---
CommanderAddin
   at CommanderAddin.CommanderAddin.<RunCommand>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at CommanderAddin.CommanderAddin.RunCommand(CommanderCommand command)
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
System.MissingMethodException
---------------------------
`

**Comment by RickStrahl** [comment]
Version mismatch. Should work with the latest version of the addin and MM.
