### ISSUE TITLE
Will not save to PDF

### ISSUE THREAD

**Issue by GregFuhrmanTT** [RickStrahl/MarkdownMonster#968]
7/12/2022 9:50:43 AM - AppDispatcher: Could not find a part of the path 'C:\Users\greg.fuhrman\OneDrive - Tyler Technologies, Inc\Documents\_e Solutions\_Warrants\_Electronic Warrant Configuration Guide\Account Administration\WAR-ESO-240-007 Electronic Warrant Account Counties Configuration Guide\__WAR-ESO-240-007 Counties Config.html'.
Could not find a part of the path 'C:\Users\greg.fuhrman\OneDrive - Tyler Technologies, Inc\Documents\_e Solutions\_Warrants\_Electronic Warrant Configuration Guide\Account Administration\WAR-ESO-240-007 Electronic Warrant Account Counties Configuration Guide\__WAR-ESO-240-007 Counties Config.html'.
Markdown Monster v2.2.2.1
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-US - en-US    
---
mscorlib
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at MarkdownMonster.Windows.GeneratePdfWindow.<ButtonGeneratePdf_Click>d__23.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\GeneratePdfWindow.xaml.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.IO.DirectoryNotFoundException

**Comment by RickStrahl** [comment]
Gonna say that's a long file path (exceeding 255 characters).

Can you go through this configuration setup here:

[Using Markdown Monster with Long Path Names](https://markdownmonster.west-wind.com/docs/_68d0r8rej.htm)

and report back what you find?

**Comment by GregFuhrmanTT** [comment]
I enabled the RegEdit, and it works with long file paths. However, I am going to save it in a different location that is a much shorter path and then drag/drop the file into the folder structure it is currently in.
Thank you for this information!

**Comment by RickStrahl** [comment]
Thanks for verifying.

Yeah - best to stick with shorter paths on Windows just because of the potential behavior issues in other applications.
